### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by githubkuyaya** [artemis1205/Absenzenverwaltung#1]
I ask you kindly to put your code online. Thanks.

**Comment by artemis1205** [comment]
Your Mom

**Comment by githubkuyaya** [comment]
On 29.11.2021 10:54, artemis1205 wrote:
Your Mom

**Comment by artemis1205** [comment]
Thank you sir:)

**Comment by githubkuyaya** [comment]
> Thank you sir:)

No problem, my guy.
Also, I can't seem to find your issues on my repo anymore, weird.

**Comment by artemis1205** [comment]
That's a pitty!

**Comment by githubkuyaya** [comment]
> That's a pitty!

~pitty~ pi**t**y
Yes, very sad indeed.

If you do not put your code online, I may have to post another friendly reminder.

**Comment by githubkuyaya** [comment]
Thanks a lot!

**Comment by artemis1205** [comment]
Sorry to bother you but the code is online!
